export const shoeProducts = [
    {
        "title": "Nike Dunk Low Premium",
        "price": 10790,
        "type": "Nike",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/12962889-796a-4231-a522-76a7842c34f0/dunk-low-shoes-KB89bk.png",
        "id": 1,
        "qty": 1,
        "description": "Nike Jeff Staple is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Trending",
        "offer": 1,
    },

    {
        "title": "Nike Dunk Low Retro",
        "price": 8290,
        "type": "Nike",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9cfd9c6d-59cb-4dac-af4f-1552ddc58d36/dunk-low-retro-shoe-66RGqF.png",
        "id": 2,
        "qty": 1,
        "description": "Created for the hardwood but taken to the streets, the Nike Dunk Low Retro returns with crisp overlays and original team colours. This basketball icon channels '80s vibes with premium leather in the upper that looks good and breaks in even better. Modern footwear technology helps bring the comfort into the 21st century.",
        "state": "Highdemand",
        "offer": 3,
    },

    {
        "title": "Nike Air Jordan 1 Low SE Craft",
        "price": 10290,
        "type": "Nike",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1773a565-253c-4f32-bd9e-9934e60ced9a/air-dunk-jumbo-shoes-wc8JrQ.png",
        "id": 3,
        "qty": 1,
        "description": "Dark, stormy and full of style. This AJ1 combines leather, suede and textiles in the upper for a tonal look with plenty of depth.",
        "state": "Bestseller",
        "offer": 5,
    },

    {
        "title": "Adidas OZWEEGO SHOES",
        "price": 12990,
        "type": "Adidas",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/811c517a86104976bc3b0bbf14b3ee72_9366/OZWEEGO_Shoes_Beige_IF6043_01_standard.jpg",
        "id": 4,
        "qty": 1,
        "description": "FUTURISTIC SHOES THAT PUT COMFORT FIRST,Inspired by '90s adidas running sneakers, the OZWEEGO shoes reimagine the bold and energetic designs of the era for today's lifestyle. With a soft suede upper and mesh overlays on a sporty base, they make a statement whether you're heading out for the day or heading into the evening. A snug fit teams up with plush drop-ins for comfort that sees you through.",
        "state": "Premium",
        "offer": 7,

    },

    {
        "title": "Adidas SUPERSTAR SHOES",
        "price": 8990,
        "type": "Adidas",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/15f901c90a9549d29104aae700d27efb_9366/Superstar_Shoes_Black_EG4959_01_standard.jpg",
        "id": 5,
        "qty": 1,
        "description": "SUPERSTAR ORIGINALS, Built for basketball, adopted by hip hop and skate, the classic leather Superstar changed the game the moment it stepped off the court. The serrated 3-Stripes mark, iconic shell style toe, and box logo makes this one of the true Originals.",
        "state": "Trending",
        "offer": 9,
    },

    {
        "title": "Adidas SUPERSTAR XLG SHOES",
        "price": 11990,
        "type": "Adidas",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e77fb686863e46c7a61eddbae1033c1b_9366/Superstar_XLG_Shoes_Green_ID4658_01_standard.jpg",
        "id": 6,
        "qty": 1,
        "description": "If you prefer life reimagined through an '80s lens, these adidas Superstar shoes are for you. The design starts with chunkier tooling for in-your-face attitude and a rock-solid look. A premium suede upper creates a luxe backdrop for the serrated 3-Stripes while a Trefoil lace jewel adds a touch of luxe. The classic rubber shell toe and herringbone-patterned outsole stay true to their roots.",
        "state": "Highdemand",
        "offer": 11,
    },

    {
        "title": "PUMA-180 STAPLE Unisex Sneakers",
        "price": 13990,
        "type": "Puma",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/396309/03/sv01/fnd/IND/fmt/png/PUMA-180-STAPLE-Unisex-Sneakers",
        "id": 7,
        "qty": 1,
        "description": "Jeff Staple is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Bestseller",
        "offer": 13,
    },

    {
        "title": "Puma RS-X Underground Drift Unisex Sneakers",
        "price": 10990,
        "type": "Puma",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/393815/02/sv01/fnd/IND/fmt/png/RS-X-Underground-Drift-Unisex-Sneakers",
        "id": 8,
        "qty": 1,
        "description": "PUMA's RS series revives the 1980s high-quality cushioning with RS (Running System) foam, an improved EVA compound offering superior rebound and enhanced stability. Originally developed by the RS Computer, this technology offers excellent energy return and a secure, confident stride, blending vintage aesthetics with advanced performance.",
        "state": "Premium",
        "offer": 15,
    },

    {
        "title": "Puma Voyage NITRO™ 2 Men's Trail Running Shoes",
        "price": 10990,
        "type": "Puma",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/376919/08/sv01/fnd/IND/fmt/png/Voyage-NITRO%E2%84%A2-2-Men's-Trail-Running-Shoes",
        "id": 9,
        "qty": 1,
        "description": "Tackle any terrain in the sturdy confines of the Voyage NITRO™ 2. In this updated version of the model, we’ve retooled the shoe with a tough new upper to accommodate a wider range of foot shapes.Our new PUMAGRIP ATR rubber outsole provides even better traction on ice, mud – whatever the surface – while the lightweight nitrogen-injected foam delivers max cushioning and responsiveness.",
        "state": "Trending",
        "offer": 0,
    },

    {
        "title": "Nike Dunk Low Premium",
        "price": 10790,
        "type": "Men's Shoes",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/12962889-796a-4231-a522-76a7842c34f0/dunk-low-shoes-KB89bk.png",
        "id": 10,
        "qty": 1,
        "description": "Nike Jeff Staple is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Highdemand",
        "offer": 0,
    },

    {
        "title": "Nike Dunk Low Retro",
        "price": 8290,
        "type": "Men's Shoes",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9cfd9c6d-59cb-4dac-af4f-1552ddc58d36/dunk-low-retro-shoe-66RGqF.png",
        "id": 11,
        "qty": 1,
        "description": "Created for the hardwood but taken to the streets, the Nike Dunk Low Retro returns with crisp overlays and original team colours. This basketball icon channels '80s vibes with premium leather in the upper that looks good and breaks in even better. Modern footwear technology helps bring the comfort into the 21st century.",
        "state": "Bestseller",
        "offer": 0,
    },

    {
        "title": "Nike Air Jordan 1 Low SE Craft",
        "price": 10290,
        "type": "Men's Shoes",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1773a565-253c-4f32-bd9e-9934e60ced9a/air-dunk-jumbo-shoes-wc8JrQ.png",
        "id": 12,
        "qty": 1,
        "description": "Dark, stormy and full of style. This AJ1 combines leather, suede and textiles in the upper for a tonal look with plenty of depth.",
        "state": "Premium",
        "offer": 0,
    },

    {
        "title": "Adidas OZWEEGO SHOES",
        "price": 12990,
        "type": "Men's Shoes",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/811c517a86104976bc3b0bbf14b3ee72_9366/OZWEEGO_Shoes_Beige_IF6043_01_standard.jpg",
        "id": 13,
        "qty": 1,
        "description": "FUTURISTIC SHOES THAT PUT COMFORT FIRST,Inspired by '90s adidas running sneakers, the OZWEEGO shoes reimagine the bold and energetic designs of the era for today's lifestyle. With a soft suede upper and mesh overlays on a sporty base, they make a statement whether you're heading out for the day or heading into the evening. A snug fit teams up with plush drop-ins for comfort that sees you through.",
        "state": "Trending",
        "offer": 0,
    },

    {
        "title": "Adidas SUPERSTAR SHOES",
        "price": 8990,
        "type": "Men's Shoes",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/15f901c90a9549d29104aae700d27efb_9366/Superstar_Shoes_Black_EG4959_01_standard.jpg",
        "id": 14,
        "qty": 1,
        "description": "SUPERSTAR ORIGINALS, Built for basketball, adopted by hip hop and skate, the classic leather Superstar changed the game the moment it stepped off the court. The serrated 3-Stripes mark, iconic shell style toe, and box logo makes this one of the true Originals.",
        "state": "Highdemand",
        "offer": 0,
    },

    {
        "title": "Adidas SUPERSTAR XLG SHOES",
        "price": 11990,
        "type": "Men's Shoes",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e77fb686863e46c7a61eddbae1033c1b_9366/Superstar_XLG_Shoes_Green_ID4658_01_standard.jpg",
        "id": 15,
        "qty": 1,
        "description": "If you prefer life reimagined through an '80s lens, these adidas Superstar shoes are for you. The design starts with chunkier tooling for in-your-face attitude and a rock-solid look. A premium suede upper creates a luxe backdrop for the serrated 3-Stripes while a Trefoil lace jewel adds a touch of luxe. The classic rubber shell toe and herringbone-patterned outsole stay true to their roots.",
        "state": "Bestseller",
        "offer": 0,
    },

    {
        "title": "PUMA-180 STAPLE Unisex Sneakers",
        "price": 13990,
        "type": "Men's Shoes",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/396309/03/sv01/fnd/IND/fmt/png/PUMA-180-STAPLE-Unisex-Sneakers",
        "id": 16,
        "qty": 1,
        "description": "Jeff Staple is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Premium",
        "offer": 0,
    },

    {
        "title": "Puma RS-X Underground Drift Unisex Sneakers",
        "price": 10990,
        "type": "Men's Shoes",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/393815/02/sv01/fnd/IND/fmt/png/RS-X-Underground-Drift-Unisex-Sneakers",
        "id": 17,
        "qty": 1,
        "description": "PUMA's RS series revives the 1980s high-quality cushioning with RS (Running System) foam, an improved EVA compound offering superior rebound and enhanced stability. Originally developed by the RS Computer, this technology offers excellent energy return and a secure, confident stride, blending vintage aesthetics with advanced performance.",
        "state": "Trending",
        "offer": 0,
    },

    {
        "title": "Puma Voyage NITRO™ 2 Men's Trail Running Shoes",
        "price": 10990,
        "type": "Men's Shoes",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/376919/08/sv01/fnd/IND/fmt/png/Voyage-NITRO%E2%84%A2-2-Men's-Trail-Running-Shoes",
        "id": 18,
        "qty": 1,
        "description": "Tackle any terrain in the sturdy confines of the Voyage NITRO™ 2. In this updated version of the model, we’ve retooled the shoe with a tough new upper to accommodate a wider range of foot shapes.Our new PUMAGRIP ATR rubber outsole provides even better traction on ice, mud – whatever the surface – while the lightweight nitrogen-injected foam delivers max cushioning and responsiveness.",
        "state": "Highdemand",
        "offer": 0,
    },

    {
        "title": "PUMA Propella Women's Sneakers",
        "price": 3540,
        "type": "Puma",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/395844/02/sv01/fnd/IND/fmt/png/PUMA-Propella-Women's-Sneakers",
        "id": 19,
        "qty": 1,
        "description": "Step into the spotlight with the PUMA Propella Women's Sneakers. Designed as a low boot with a lacing system, these sneakers inherit the Carina DNA and features a low to the ground tooling and a sleeker upper for a clean court silhouette encapsulating the essence of sneakerhead culture.",
        "state": "Bestseller",
        "offer": 0,
    },

    {
        "title": "Puma Cruise Rider Silk Road Women's Sneakers",
        "price": 7490,
        "type": "Puma",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374822/02/sv01/fnd/KOR/fmt/png/Pulsar-Wedge-Tonal-Women's-Sneakers",
        "id": 20,
        "qty": 1,
        "description": "Soar with style in the Cruise Rider Silk Road Women's Sneakers. Featuring a durable colorblock upper and secure lace closure, these sneakers fuse comfort with functionality. Emblazoned with the iconic PUMA formstrip, they represent the perfect blend of modern design and classic branding.",
        "state": "Premium",
        "offer": 0,


    },
    {
        "title": "Puma CA. Flyz PRM Women's Sneakers",
        "price": 10990,
        "type": "Puma",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/396099/03/sv01/fnd/IND/fmt/png/CA.-Flyz-PRM-Women's-Sneakers",
        "id": 21,
        "qty": 1,
        "description": "Meet CA. Flyz. This new silhouette is bringing a sport-inspired twist to the CA family. Its design features a traditional basketball upper, a chunkier tooling, and a new construction for lightness and comfort – making it the perfect everyday kick to bring a sporty edgy to any ‘fit.",
        "state": "Trending",
        "offer": 0,
    },

    {
        "title": "Adidas GAZELLE SHOES",
        "price": 10990,
        "type": "Adidas",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d3a63bc48eb64c8dbcf7af63016fb749_9366/Gazelle_Shoes_Orange_IE5137_01_standard.jpg",
        "id": 22,
        "qty": 1,
        "description": "CLASSIC SHOES RETURN TO THE SCENE.From football fans in the '60s and '70s to skaters and indie rockers in the '90s, the adidas Gazelle Shoes have traversed the entirety of our cultural landscape. This pair has the same materials, proportions and textures as the original. Seasonal colours add a trendy update for style in every step.",
        "state": "Highdemand",
        "offer": 0,
    },

    {
        "title": "Adidas ASTIR SHOES",
        "price": 8990,
        "type": "Adidas",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/48a987f917cd4b229540729ab10d9c2f_9366/Astir_Shoes_White_IE9630_01_standard.jpg",
        "id": 23,
        "qty": 1,
        "description": "STYLISH SHOES THAT GIVE AN EXPRESSIVE REMIX TO A WELL-KNOWN RUNNING DESIGN.Injected with the bold energy of the original 2000s design, these adidas Astir shoes bring a trendy remix to the OG silhouette. A bright zebra print on their lightweight mesh upper shows off a daring attitude, while oversized TPU eyelets add a playful twist.",
        "state": "Bestseller",
        "offer": 0,
    },

    {
        "title": "Adidas FORUM BOLD STRIPES SHOES",
        "price": 10990,
        "type": "Adidas",
        "image": "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/0109f06d08004c369341af56012818cf_9366/Forum_Bold_Stripes_Shoes_Black_ID6844_01_standard.jpg",
        "id": 24,
        "qty": 1,
        "description": "EXPRESS YOURSELF IN THIS NEW TAKE ON AN OG SHOE.Put your true personality on display in these adidas Forum Bold Stripes Shoes. A rebuild of the 1984 Forum, these trainers are true to all the original details, pattern and materials. Oversized Trefoil elements accentuate a playful style.",
        "state": "Premium",
        "offer": 0,
    },

    {
        "title": "Nike Air Force 1 Shadow",
        "price": 8990,
        "type": "Nike",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4621066a-6e19-49e5-a2d7-4e7e5eade298/air-force-1-shadow-shoes-mN8Glx.png",
        "id": 25,
        "qty": 1,
        "description": "Nike is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Trending",
        "offer": 0,
    },

    {
        "title": "Nike Gamma Force",
        "price": 8490,
        "type": "Nike",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3928eb18-1f47-4554-8e18-1788f6d5c4f8/gamma-force-shoes-CbTnH1.png",
        "id": 26,
        "qty": 1,
        "description": "Nike is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Highdemand",
        "offer": 0,
    },

    {
        "title": "Nike Adjust Force",
        "price": 9690,
        "type": "Nike",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/10af3adf-cba7-4681-bda7-d3f169835329/adjust-force-sandals-sjkn5x.png",
        "id": 27,
        "qty": 1,
        "description": "Nike is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Bestseller",
        "offer": 0,
    },

    {
        "title": "PUMA Propella Women's Sneakers",
        "price": 3540,
        "type": "Women's Shoes",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/395844/02/sv01/fnd/IND/fmt/png/PUMA-Propella-Women's-Sneakers",
        "id": 28,
        "qty": 1,
        "description": "Step into the spotlight with the PUMA Propella Women's Sneakers. Designed as a low boot with a lacing system, these sneakers inherit the Carina DNA and features a low to the ground tooling and a sleeker upper for a clean court silhouette encapsulating the essence of sneakerhead culture.",
        "state": "Premium",
        "offer": 0,
    },

    {
        "title": "Puma Cruise Rider Silk Road Women's Sneakers",
        "price": 7490,
        "type": "Women's Shoes",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374822/02/sv01/fnd/KOR/fmt/png/Pulsar-Wedge-Tonal-Women's-Sneakers",
        "id": 29,
        "qty": 1,
        "description": "Soar with style in the Cruise Rider Silk Road Women's Sneakers. Featuring a durable colorblock upper and secure lace closure, these sneakers fuse comfort with functionality. Emblazoned with the iconic PUMA formstrip, they represent the perfect blend of modern design and classic branding.",
        "state": "Trending",
        "offer": 0,
    },

    {
        "title": "Puma CA. Flyz PRM Women's Sneakers",
        "price": 10990,
        "type": "Women's Shoes",
        "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/396099/03/sv01/fnd/IND/fmt/png/CA.-Flyz-PRM-Women's-Sneakers",
        "id": 30,
        "qty": 1,
        "description": "Meet CA. Flyz. This new silhouette is bringing a sport-inspired twist to the CA family. Its design features a traditional basketball upper, a chunkier tooling, and a new construction for lightness and comfort – making it the perfect everyday kick to bring a sporty edgy to any ‘fit.",
        "state": "Highdemand",
        "offer": 0,
    },

    {
        "title": "Adidas GAZELLE SHOES",
        "price": 10990,
        "type": "Women's Shoes",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d3a63bc48eb64c8dbcf7af63016fb749_9366/Gazelle_Shoes_Orange_IE5137_01_standard.jpg",
        "id": 31,
        "qty": 1,
        "description": "CLASSIC SHOES RETURN TO THE SCENE.From football fans in the '60s and '70s to skaters and indie rockers in the '90s, the adidas Gazelle Shoes have traversed the entirety of our cultural landscape. This pair has the same materials, proportions and textures as the original. Seasonal colours add a trendy update for style in every step.",
        "state": "Bestseller",
        "offer": 0,
    },

    {
        "title": "Adidas ASTIR SHOES",
        "price": 8990,
        "type": "Women's Shoes",
        "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/48a987f917cd4b229540729ab10d9c2f_9366/Astir_Shoes_White_IE9630_01_standard.jpg",
        "id": 32,
        "qty": 1,
        "description": "STYLISH SHOES THAT GIVE AN EXPRESSIVE REMIX TO A WELL-KNOWN RUNNING DESIGN.Injected with the bold energy of the original 2000s design, these adidas Astir shoes bring a trendy remix to the OG silhouette. A bright zebra print on their lightweight mesh upper shows off a daring attitude, while oversized TPU eyelets add a playful twist.",
        "state": "Premium",
        "offer": 0,
    },

    {
        "title": "Adidas FORUM BOLD STRIPES SHOES",
        "price": 10990,
        "type": "Women's Shoes",
        "image": "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/0109f06d08004c369341af56012818cf_9366/Forum_Bold_Stripes_Shoes_Black_ID6844_01_standard.jpg",
        "id": 33,
        "qty": 1,
        "description": "EXPRESS YOURSELF IN THIS NEW TAKE ON AN OG SHOE.Put your true personality on display in these adidas Forum Bold Stripes Shoes. A rebuild of the 1984 Forum, these trainers are true to all the original details, pattern and materials. Oversized Trefoil elements accentuate a playful style.",
        "state": "Trending",
        "offer": 0,
    },

    {
        "title": "Nike Air Force 1 Shadow",
        "price": 8990,
        "type": "Women's Shoes",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4621066a-6e19-49e5-a2d7-4e7e5eade298/air-force-1-shadow-shoes-mN8Glx.png",
        "id": 34,
        "qty": 1,
        "description": "Nike is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Highdemand",
        "offer": 0,
    },

    {
        "title": "Nike Gamma Force",
        "price": 8490,
        "type": "Women's Shoes",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3928eb18-1f47-4554-8e18-1788f6d5c4f8/gamma-force-shoes-CbTnH1.png",
        "id": 35,
        "qty": 1,
        "description": "Nike is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Bestseller",
        "offer": 0,
    },

    {
        "title": "Nike Adjust Force",
        "price": 9690,
        "type": "Women's Shoes",
        "image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/10af3adf-cba7-4681-bda7-d3f169835329/adjust-force-sandals-sjkn5x.png",
        "id": 36,
        "qty": 1,
        "description": "Nike is recognized in the streetwear world for his iconic work that blends streetwear and design. He is the owner of Staple Design - a clothing collection, creative agency and store in New York that collaborates with many high caliber brands. And he was happy to rework the PUMA-180, a pair dedicated to the skate culture of the late 90s and 2000s, which is based on oversized styling, chunky shapes and a technical lo-fi upper.",
        "state": "Premium",
        "offer": 0,
    },
]